### ISSUE TITLE
Want to add Dijkstra algorithm 

### ISSUE THREAD

**Issue by sdas2k3** [torchdotonions/hacktoberfest2023-DSA#6]
Hey @torchdotonions I want to contribute to this repo by adding the Dijkstra algorithm which is a famous graph algorithm that is used to find the shortest path for any weighted, directed graph with non-negative weights. Please assign this issue to me. I will write my code in C++ with proper explanation and time and space complexity.

**Comment by torchdotonions** [comment]
Yes, open PR regarding it.
